### ISSUE TITLE
Map - Clicking on Table and Map again deactivates the map

### ISSUE THREAD

**Issue by kopitek8** [collective-service/ifrc-gates-dashboard#446]
### Steps to Replicate

Outbreak: Ebola
Region: ESAR

### Issue

When clicking on the table and back on map, map is not active (see screenshot below)

### Screenshot

![Image](https://user-images.githubusercontent.com/25280806/205223530-55d77367-816c-470c-98db-0268dc0e2fcc.png)

**Comment by kopitek8** [comment]
UPDATED FILTERS:

Cholera - ESAR

**Comment by kopitek8** [comment]
Error: The layer 'country›country-fill' does not exist in the map's style and cannot be queried for features.
    at $t.queryRenderedFeatures (mapbox-gl.js:35:117290)
    at Map.queryRenderedFeatures (mapbox-gl.js:35:435878)
    at Map.i (index.es.js:1437:39)
    at Map.fire (mapbox-gl.js:31:18369)
    at ti.mousemove (mapbox-gl.js:35:360433)
    at zi.handleEvent (mapbox-gl.js:35:385096)
    at HTMLDivElement.i (helpers.js:74:23)
