### ISSUE TITLE
Cannot read properties of undefined (reading 'indicatorDescription')

### ISSUE THREAD

**Issue by kopitek8** [collective-service/ifrc-gates-dashboard#458]
React ErrorBoundary Error: Cannot read properties of undefined (reading 'indicatorDescription')
  at H1 (./app/views/Dashboard/Country/index.tsx:398:9)
  at S3 (./app/views/Dashboard/index.tsx:148:9)
...
(1 additional frame(s) were not displayed)

TypeError: Cannot read properties of undefined (reading 'indicatorDescription')
  at H1 (./app/views/Dashboard/Country/index.tsx:1001:73)
  at Array.forEach (<anonymous>)
  at Array.forEach (<anonymous>)
...
(29 additional frame(s) were not displayed)

**Comment by kopitek8** [comment]
Please do let me know if you want the full Sentry error, I'll forward the email then
